dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-update

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

script:
  - bin/phpunit

after_success:
  - travis_retry composer require php-coveralls/php-coveralls
  - travis_retry bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
